spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  security:
    user:
      name: admin
      password: 000000
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.164.148/BreakingWind?tinyInt1isBit=false
    username: root
    password: lengzq@Xyq123
  #Redis配置
  redis:
    database: 0
    host: 47.94.164.148
    port: 6379
    password: abc123
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  #缓存配置
  cache:
    cache-names: menus_cache;
    redis:
      time-to-live: 1800s
#端口配置
server:
  port: 8082

logging:
  config: src/main/resources/config/logback.xml

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.leng.oldass
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl